### ISSUE TITLE
BikeNYC数据集不一致

### ISSUE THREAD

**Issue by pengzhangzhi** [LibCity/Bigscity-LibCity-Datasets#33]
link: https://www.citibikenyc.com/system-data
BikeNYC数据，202101-citibike-tripdata.csv 及以前的数据字段为：'tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender' 一共15个，而之后的'ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual' 只有13个，当前数据预处理脚本nycbike.py 只能处理之前的数据。对于之后的数据无法处理。

**Comment by pengzhangzhi** [comment]
我已经解决好了，稍后等我PR

**Comment by molua** [comment]
> link: https://www.citibikenyc.com/system-data BikeNYC数据，202101-citibike-tripdata.csv 及以前的数据字段为：'tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender' 一共15个，而之后的'ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual' 只有13个，当前数据预处理脚本nycbike.py 只能处理之前的数据。对于之后的数据无法处理。

你好 请问BikeNYC数据集就是在link: https://www.citibikenyc.com/system-data这个链接里下载的吗

**Comment by aptx1231** [comment]
> > link: https://www.citibikenyc.com/system-data BikeNYC数据，202101-citibike-tripdata.csv 及以前的数据字段为：'tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender' 一共15个，而之后的'ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual' 只有13个，当前数据预处理脚本nycbike.py 只能处理之前的数据。对于之后的数据无法处理。
> 
> 你好 请问BikeNYC数据集就是在link: https://www.citibikenyc.com/system-data 这个链接里下载的吗

是的，也可以下载我们处理过的数据集。https://drive.google.com/drive/folders/1g5v2Gq1tkOq8XO0HDCZ9nOTtRpB6-gPe
