### ISSUE TITLE
about the field 'dyna_id' in the result file xx.dyna

### ISSUE THREAD

**Issue by nehSgnaiL** [LibCity/Bigscity-LibCity-Datasets#43]
Hi, thanks for the incredible work. It seems the expected field was missing during the transform process.

#### Describe the bug

The field 'dyna_id' in the result file xx.dyna generated by foursquare.py was None.
ref. code: https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/145f66256a9cc056826abe06d33d8d0e13c926cf/foursquare.py#L63

#### Code to Reproduce
https://github.com/LibCity/Bigscity-LibCity-Datasets/blob/145f66256a9cc056826abe06d33d8d0e13c926cf/foursquare.py

#### Expected behavior

dyna_id should be clarified in ```dyna['dyna_id'] = dyna.index``` or other ways.
#### Actual result

output file (sample):
> dyna_id,type,time,entity_id,location
> ,trajectory,2012-04-03T14:00:09Z,0,2388
> ,trajectory,2012-04-04T14:00:09Z,0,2388
> ...
#### Versions

Windows-10-10.0.19043-SP0
Python 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]

**Comment by aptx1231** [comment]
@WenMellors

**Comment by WenMellors** [comment]
Thanks for your comment. The bug is just as you said, and we fix it now.
