### ISSUE TITLE
NYCBike20160708: gridod file missing

### ISSUE THREAD

**Issue by SonghuaHu-UMD** [LibCity/Bigscity-LibCity-Datasets#46]
The gridod file is needed when running the STDN ([Revisiting Spatial-Temporal Similarity: A Deep Learning Framework for Traffic Prediction](https://arxiv.org/abs/1803.01254)), but is missing in the [Google Drive](https://drive.google.com/drive/folders/1g5v2Gq1tkOq8XO0HDCZ9nOTtRpB6-gPe).

I created it following your code "nycbike20160708.py". You can now access it via the following link:

https://drive.google.com/file/d/1KOIj8w2Nf9Sd5TDV7IuJwZOUxOz3PJ6_/view?usp=sharing

**Comment by aptx1231** [comment]
Thank you, I don't unload it because it is two big.

**Comment by aptx1231** [comment]
The dataset NYCTaxi20150103 is similarly missing gridod, which I will upload later to the [Google Drive](https://drive.google.com/drive/folders/1g5v2Gq1tkOq8XO0HDCZ9nOTtRpB6-gPe).
